services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: aspnet_api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MongoDbSettings__ConnectionString: "mongodb://admin:password@mongodb:27017"
      MongoDbSettings__DatabaseName: "MyDatabase"

volumes:
  mongo_data:

